//
//  AracGostergePaneliVeri.swift
//  SurucuEhliyeti
//
//  Created by Mehmet Ali Kılıçlı on 13.04.2023.
//

import Foundation

struct AracGostergeIsaret {
    var id: Int
    var aracGostergeImage : String
    var aracGosterge : String
}

class AGPIVeriler {
    static let shared = AGPIVeriler()
    
    func getAracGostergePaneliVeriler() -> [AracGostergeIsaret] {
        
        var aracGostergePaneliVeriler : [AracGostergeIsaret] = [
            AracGostergeIsaret(id: 1, aracGostergeImage: "agpi1", aracGosterge: "Motor Sıcaklığı Uyarı Işığı; Motorun soğutma sıvısını aşırı ısıttığını gösterir. Aracınızdaki en önemli üç ikaz lambasından biri (Diğer Yağ Lambası ve Şarj Lambası). Aracınızın gösterge panelinde bu kırmızı lambayı gördüğünüzde aracınızı en kısa sürede durdurmalı ve motorun uygun sıcaklığa soğumasını beklemelisiniz. Arabanız soğuk olsa bile bu durumda devam etmeniz önerilmez. Aracınızı en yakın servise götürmeniz tavsiye edilir. Bu lamba yanıkken aracınızı sürmeye devam ederseniz aracınızın motoruna maddi açıdan büyük zararlar verebilirsiniz."),
            AracGostergeIsaret(id: 2, aracGostergeImage: "agpi2", aracGosterge: "Yağ basıncı İkaz lambası; Yağ aracınızın can damarıdır. Tüm motor sistemi yağlama sayesinde çalışmaktadır. Tıpkı insan vücudunun su ihtiyacı gibi. En önemlisi, acil müdahale gerektiren uyarı lambasıdır. Bu lamba yanarsa, aracınızın yağ seviyesi düşüktür. Motorunuz soğuduktan sonra en kısa sürede aracınızı durdurup yağ seviyesini kontrol etmelisiniz. Aracınızı bu ikaz lambası yanarsa sürmemelisiniz."),
            AracGostergeIsaret(id: 3, aracGostergeImage: "agpi3", aracGosterge: "Akü Şarj İkaz Lambası; Akü şarj ikaz lambası, arabanızın şarj dinamosunda bir sorun olduğu ve arabanızın yalnızca aküyle çalıştığı anlamına gelir. Akü uyarısının nedeni ne olursa olsun, en güvenli seçenek aracınızı servise götürüp arızayı kontrol ettirmektir. Başınız belaya girdiğinde radyonuzu ve klima sisteminizi kapatın ve güvenli bir şekilde tamirhaneye gitmeyi düşünün."),
            AracGostergeIsaret(id: 4, aracGostergeImage: "agpi4", aracGosterge: "El Freni İkaz Lambası; El freninin çekili olduğunu gösteren bir uyarı ışığıdır."),
            AracGostergeIsaret(id: 5, aracGostergeImage: "agpi5", aracGosterge: "El Freni İkaz Lambası; El freninin çekili olduğunu gösteren bir uyarı ışığıdır."),
            AracGostergeIsaret(id: 6, aracGostergeImage: "agpi6", aracGosterge: "Park Freni İkaz Lambası; Otomatik vitesli araçlarda vitesi park konumuna getirdiğinizde yanar. (P)"),
            AracGostergeIsaret(id: 7, aracGostergeImage: "agpi7", aracGosterge: "Hava Yastığı İkaz Lambası; Bu lamba yandığında, hava yastığı sistemi çalışmıyordur. Servise gitmeniz tavsiye edilir. Bazı durumlarda yolcu koltuğunda biri otururken, emniyet kemeri takılmadığında yanabilir."),
            AracGostergeIsaret(id: 8, aracGostergeImage: "agpi8", aracGosterge: "Emniyet Kemeri İkaz Işığı; Emniyet kemerinin takılı olmadığını gösteren uyarı lambası."),
            AracGostergeIsaret(id: 9, aracGostergeImage: "agpi9", aracGosterge: "Şanzıman Sıcaklığı İkaz Lambası: Şanzıman, uygun olmayan bir sıcaklıkta çalıştığını gösteren bir uyarı sembolüdür. Şanzıman yağı seviyesini ve motor soğutma suyu seviyesini kontrol edin. Araç N vitesteyken 5 dakika rölantide soğumasını bekleyin."),
            AracGostergeIsaret(id: 10, aracGostergeImage: "agpi10", aracGosterge: "Araç Güvenlik Uyarı Işığı; Bu gösterge ışığı yaklaşık 15 saniye yanıp söner. Araç güvenlik alarmı çaldığı için yanıp söner ve alarm çaldığında otomatik olarak kapanır."),
            AracGostergeIsaret(id: 11, aracGostergeImage: "agpi11", aracGosterge: "Elektronik Gaz Kelebeği Kontrol İkaz Lambası; Bu gösterge sembolü, Elektronik Gaz Kelebeği Kontrol sisteminde bir arıza olduğunu belirtmek için yanar. Bu ışık uzun süre yanıp sönerse aracınızı hemen durdurup PARK konumuna almalısınız. En kısa sürede  servis istasyonuyla iletişime geçmelisiniz.."),
            AracGostergeIsaret(id: 12, aracGostergeImage: "agpi12", aracGosterge: "Önde Araç Göstergesi Uyarı Işığı; Bu gösterge paneli ışığı, arabanızın önünde bir araç olduğunu ve çarpışmayı önlemek için hızınızı azaltmanız gerektiğini size göstermek için yanıp söner."),
            AracGostergeIsaret(id: 13, aracGostergeImage: "agpi13", aracGosterge: "Şeritte kalma yardımcısı uyarı lambası; Günümüz teknolojisi ile üretilen araçlarda sinyal kullanılmadan şerit değiştirildiğinde yanan ikaz lambasıdır."),
            AracGostergeIsaret(id: 14, aracGostergeImage: "agpi14", aracGosterge: "Motor Arıza Lambası; Motor arıza uyarı lambası. En sık yanan lambalardan biridir. Çoğu aracın 2 seviyesi vardır. Işık AÇIK kalırsa ve sabit yanarsa, ciddiye alınmalıdır. Ancak ışık yanıp sönüyorsa bu daha ciddi bir soruna işaret eder ve araç kullanılmadan servise götürülmesi tavsiye edilir. Motor arıza lambası birkaç nedenden dolayı yanabilir. En yaygın olanı avans ayarıdır. Motor sistemi açılır ve araç doğru şekilde takılmadığında yanar. Diğer yaygın nedenler şunları içerebilir; kalitesiz yakıt, lambda sensörü arızası, katalitik konvertör arızası, egr arızası."),
            AracGostergeIsaret(id: 15, aracGostergeImage: "agpi15", aracGosterge: "Motor Arıza Lambası; Motor arıza uyarı lambası. En sık yanan lambalardan biridir. Çoğu aracın 2 seviyesi vardır. Işık AÇIK kalırsa ve sabit yanarsa, ciddiye alınmalıdır. Ancak ışık yanıp sönüyorsa bu daha ciddi bir soruna işaret eder ve araç kullanılmadan servise götürülmesi tavsiye edilir. Motor arıza lambası birkaç nedenden dolayı yanabilir. En yaygın olanı avans ayarıdır. Motor sistemi açılır ve araç doğru şekilde takılmadığında yanar. Diğer yaygın nedenler şunları içerebilir; kalitesiz yakıt, lambda sensörü arızası, katalitik konvertör arızası, egr arızası."),
            AracGostergeIsaret(id: 16, aracGostergeImage: "agpi16", aracGosterge: "Dizel Partikül Filtresi (DPF) İkaz Lambası: Partikül filtresi, egzoz gazlarının dışarı üflenen havayı kirleten ve daha az zararlı gazın dışarı atılmasını sağlayan kısmıdır. Bu lamba dizel araç üzerinde bulunur ve yandığında aracınızın egzoz sistemi veya farklı maddelerden dolayı tıkandığını gösterir.Dizel partikül filtresi açıkken, aracınızın hava akımına düştüğünü fark edebilirsiniz. Çok tıkanırsa aracınız ara sıra durabilir. Aracınızın egzoz emisyon değerleri yükselebilir. Araç çalışırken 10-15 dakika yüksek hızlarda kullanırsanız kurum temizlenebilir ve lamba sönebilir. Sönmezse servise gitmeniz önerilir."),
            AracGostergeIsaret(id: 17, aracGostergeImage: "agpi17", aracGosterge: "Kızdırma Bujisi İkaz Lambası; Bu ikaz ışığı dizel araçlarda bulunur ve aracın çalışması için gerekli olan ateşlemeyi ayarlayan parçadır. Benzinli araçlarda ateşleme buji ile, dizel araçlarda ise soğuk havalarda ısıtma bujisi ile yapılır. Soğuk havalarda aracınız çalışmıyorsa ve bu arıza lambası yanıyorsa kalorifer baraları çalışmıyordur ve değiştirilmesi gerekir."),
            AracGostergeIsaret(id: 18, aracGostergeImage: "agpi18", aracGosterge: "Düşük Yakıt Göstergesi Sembolü; Aracınızın yakıtı azaldığında yanan uyarı lambasıdır. Bu lambanın yanması deponuzda markanıza göre değişen oranlarda akaryakıt olduğunu gösterir. Bu yakıt miktarı aracınızın kullanma kılavuzunda yazılıdır. Depodaki yakıt ortalama 5 ile 8 litre arasında olduğunda yanar."),
            AracGostergeIsaret(id: 19, aracGostergeImage: "agpi19", aracGosterge: "ABS uyarı lambası; Kontak anahtarı “ON” konumundayken kontak açılmıyorsa, yanma sonrası AÇIK konuma geçmiyorsa arızalı demektir, seyir halinde ise aracınızı dikkatli kullanmalısınız, orta hızda sürün. ve sert fren yapmaktan kaçının."),
            AracGostergeIsaret(id: 20, aracGostergeImage: "agpi20", aracGosterge: "Sport Mod; Bu uyarı işareti, spor modunun etkinleştirildiğini gösterir."),
            AracGostergeIsaret(id: 21, aracGostergeImage: "agpi21", aracGosterge: "Servis 4wd İkaz Lambası; Gösterge panelindeki dört tekerlekten çekiş uyarı işareti ve 4WD lambası yanıyorsa, sistemde bir arıza olabilir"),
            AracGostergeIsaret(id: 22, aracGostergeImage: "agpi22", aracGosterge: "Elektronik Stabilite Kontrolü Aktif İkaz Işığı; Araç çekiş kontrolü/kaymayı önleme veya elektronik denge sistemi kullanımdayken yanar. Genellikle koşulların kaygan olduğunu gösteren bir gösterge ışığıdır."),
            AracGostergeIsaret(id: 23, aracGostergeImage: "agpi23", aracGosterge: "Üçgem İçinde Ünlem İkaz Lambası; Araçların gösterge panelinde yanan sarı üçgen içindeki ünlem işareti, jenerik ikaz ışığı veya servis ışığı olarak da bilinir. Arabanızın gösterge panelinde bu ışık yandıysa, bu genellikle acil bir durum olmadığını, ancak arabanızda düzeltilmesi gereken bir sorun olduğunu gösterir. Renk, iyi huylu bir mesaj için beyazdan dikkat edilmesi gereken sarıya, kritik kırmızıya dönüşür."),
            AracGostergeIsaret(id: 24, aracGostergeImage: "agpi24", aracGosterge: "Kapı açık ikaz ışığı; Arabanızdaki bagaj dahil, tek bir kapı açıldığında veya kapandığında yanan bir uyarı lambası."),
            AracGostergeIsaret(id: 25, aracGostergeImage: "agpi25", aracGosterge: "Bagaj kapağı açık ikaz lambası; Bagaj bölmesinin açık olduğunu gösteren araç ön panelli işaretler."),
            AracGostergeIsaret(id: 26, aracGostergeImage: "agpi26", aracGosterge: "Kaput Açık Uyarı Işığı; Motor kaputu açık ise panelde bu araç ikaz ışığı yanacaktır."),
            AracGostergeIsaret(id: 27, aracGostergeImage: "agpi27", aracGosterge: "Elektrikli Park İkaz Lambası; Bu uyarı simgesi, el freni sisteminde teknik bir sorun/kusur olduğunu ve acil servis gerektiğini belirtir."),
            AracGostergeIsaret(id: 28, aracGostergeImage: "agpi28", aracGosterge: "Dört Çeker İkaz Lambası; Bu gösterge paneli uyarı lambası yanarsa, aracınızın AWD yani 4 çeker  sisteminde bir sorun olduğunu gösterir. Aracınızı servis sağlayıcınıza götürmeniz en doğrusu olacaktır."),
            AracGostergeIsaret(id: 29, aracGostergeImage: "agpi29", aracGosterge: "Direksiyon İkaz Lambası; Hidrolik ve/veya elektrikli direksiyon sistemine sahip araçlarda, sistemde meydana gelen problem ve arızalar gösterge panelinde bulunan kırmızı veya sarı renkli direksiyon işareti ile gösterge panelinde görülebilmektedir."),
            AracGostergeIsaret(id: 30, aracGostergeImage: "agpi30", aracGosterge: "Yakıt Filtresinde Su Uyarı Işığı; Bu motor ikaz ışığı, yakıt filtresindeki su seviyesinin arttığını gösterir."),
            AracGostergeIsaret(id: 31, aracGostergeImage: "agpi31", aracGosterge: "Gevşek Yakıt Doldurma Kapağı Uyarı Işığı; Tam kapatılmamış yada gevşek bırakılmış yakıt kapağı uyarısı. Yakıt kapağını kontrol edin"),
            AracGostergeIsaret(id: 32, aracGostergeImage: "agpi32", aracGosterge: "Düşük yıkama sıvısı uyarı lambası; Kullanıcıya, ön cam yıkama sıvısının azaldığını veya bittiğini bildiren araba uyarı ışığı."),
            AracGostergeIsaret(id: 33, aracGostergeImage: "agpi33", aracGosterge: "Hız sabitleyici uyarı lambası; ACC şu anda kullanılamıyor. Güvenli olduğunda, aracı durdurun ve motoru kapatın. Aracı yeniden çalıştırın ve radarda kir, buz vb. olup olmadığını kontrol edin. Engel olup olmadığını kontrol edin. Uyarı lambası yanık kalırsa, lütfen yardım için en yakın yetkili servisi ziyaret edin."),
            AracGostergeIsaret(id: 34, aracGostergeImage: "agpi34", aracGosterge: "Çekiş Kapalı İkaz Lambası; Çoğu çekiş kontrol sistemi, sistem kar veya yağmur gibi bir çekiş kaybı algıladığında uyarı ışığını yakar. Tipik olarak ışık, çekişi sürdürmek için sistem müdahale ettiğinde görülür. Çekiş veya denge sisteminizin nasıl çalıştığını öğrenmek için aracınızın kullanım kılavuzundaki bölümü okumak iyi bir fikirdir. Çekiş kontrol lambası yanar ve yanıp sönmeden yanık kalırsa, çekiş kontrol sistemi devre dışıdır ve çekiş kontrolü yoktur. Hatta sürücü bilgi merkezi tarafından, çekiş kontrol sisteminin kapatıldığı ve özellikle su, buz ve kar üzerinde sürerken ekstra dikkat gösterilmesi gerektiği konusunda uyarıda bulunan bir mesaj bile verilebilir. Yukarıdaki koşullardan herhangi birini doğru bir şekilde çözmenin tek yolu, kalifiye bir tamirhanede araca doğru şekilde teşhis koymaktır. Tamir atölyesine her zaman tam bir bilgisayar sistemi taraması yaptırın."),
            AracGostergeIsaret(id: 35, aracGostergeImage: "agpi35", aracGosterge: "Elektronik denge kontrolü kapalı uyarı ışığı; ESC sistemi her araçta aynı şekilde çalışmaz. Bu nedenle, sizinkinin nasıl çalıştığını anlamak için üreticinizin kılavuzuna başvurmak her zaman önemlidir. ESC ışığı genellikle araç kontrolünü kaybettiğinde yanar ve bir arıza algılandığında veya sistem manuel olarak kapatıldığında yanık kalır."),
            AracGostergeIsaret(id: 36, aracGostergeImage: "agpi36", aracGosterge: "Lastik basıncı izleme sistemi tpms uyarı ışığı; Aracınızdaki lastik basıncı düşük veya sistemde bir sorun var."),
            AracGostergeIsaret(id: 37, aracGostergeImage: "agpi37", aracGosterge: "Şeritten Ayrılma Uyarı Işığı; Şerit değiştirme ışığı, aracın sinyal vermeden mevcut şeridinden ayrıldığının algılandığı anlamına gelir. Şeritte kalmanıza yardımcı olabilir."),
            AracGostergeIsaret(id: 38, aracGostergeImage: "agpi38", aracGosterge: "Akıllı Giriş Sistemi Gösterge Işığı; Akıllı giriş ve çalıştırma sisteminde bir arıza olduğunu gösterir veya bu uyarı lambası, kontak anahtarının arızalı olduğunu bildirir."),
            AracGostergeIsaret(id: 39, aracGostergeImage: "agpi39", aracGosterge: "Şerit değiştirme uyarı ışığı; Günümüz teknolojisi ile üretilen araçlarda sinyal kullanılmadan şerit değiştirildiğinde yanan ikaz lambasıdır."),
            AracGostergeIsaret(id: 40, aracGostergeImage: "agpi40", aracGosterge: "Süspansiyon Kontrol İkaz Lambası; Süspansiyon sistemi arızalanırsa bu uyarı lambası yanacaktır."),
            AracGostergeIsaret(id: 41, aracGostergeImage: "agpi41", aracGosterge: "Otomatik şanzıman ikaz ışığı; Otomatik şanzımanda bir sorun varsa gösterge panelinde bu ikaz ışığı sarı veya kırmızı renkte yanar."),
            AracGostergeIsaret(id: 42, aracGostergeImage: "agpi42", aracGosterge: "Çarpışmayı önleyen fren sistemi uyarı lambası; Işık, sistem kapatıldığında, radar sensörü kirlendiğinde veya tıkandığında veya sistemde bir arıza olduğunda yanar. Son durumda, teşhis ve onarım için aracınızı bayiinize veya yetkili servise götürün."),
            AracGostergeIsaret(id: 43, aracGostergeImage: "agpi43", aracGosterge: "Kör nokta gösterge ışığı; Bu ışık, kör noktanızda bir araç veya engel algılandığında yanar."),
            AracGostergeIsaret(id: 44, aracGostergeImage: "agpi44", aracGosterge: "Ön duyu uyarı ışığı; Bu sistem sürücü sert bir şekilde frene bastığında elektronik stabilite kontrol sistemini tetikleyen sensörler kullanır. Buna karşılık elektrik motorları, olası bir kazaya hazırlık olarak ön emniyet kemerlerini sıkar.  Ayrıca basit, dörtlü ikaz flaşörlerini yakar, camları ve açılır tavanı (varsa) kapatır. Sistem, sürücünün çarpışmadan kaçınmasına yardımcı olmaz. Bunun yerine, meydana gelmesi durumunda ciddi yaralanma olasılığını azaltmak için kabini darbeye hazırlar."),
            AracGostergeIsaret(id: 45, aracGostergeImage: "agpi45", aracGosterge: "Yokuş iniş kontrolü uyarı lambası; Yokuş iniş kontrolü gösterge lambası sürekli AÇIK ise, sistem AÇIKTIR ve devreye alınmıştır ve araç hızını kontrol etmektedir. Yokuş iniş kontrolü gösterge ışığı yanıp sönüyorsa, sistem AÇIK durumdadır ancak etkinleştirilmemiştir ve araç hızını kontrol etmemektedir."),
            AracGostergeIsaret(id: 46, aracGostergeImage: "agpi46", aracGosterge: "Sinyal gösterge ışığı;  Sinyalin açık olduğunu gösterir. Sinyal kolunu indirdiğinizde sola dönüş, yukarı kaldırdığınızda sağa dönüşü gösterir."),
            AracGostergeIsaret(id: 47, aracGostergeImage: "agpi47", aracGosterge: "Stop/start sistemi ikaz lambası; Birçok yeni araba modelinde, kırmızı ışıktayken motorunuzu durdurarak yakıt tasarrufu yapmanıza yardımcı olan motor durdurma/çalıştırma özelliğidir. Bu uyarı ışığı, devredeyken yanabilir. Manuel açılıp kapatılabilir."),
            AracGostergeIsaret(id: 48, aracGostergeImage: "agpi48", aracGosterge: "Hız sabitleyici gösterge ışığı; Seyir kontrolünün etkinleştirildiğini gösteren gösterge ışığı."),
            AracGostergeIsaret(id: 49, aracGostergeImage: "agpi49", aracGosterge: "Far Açık Gösterge Işığı; Kısa farların ve stop lambalarının açık olduğunu gösterir"),
            AracGostergeIsaret(id: 50, aracGostergeImage: "agpi50", aracGosterge: "Kısa farlar; Bu işaret, kısa farlar açıkken ön panelde görünür."),
            AracGostergeIsaret(id: 51, aracGostergeImage: "agpi51", aracGosterge: "Uzun far gösterge uyarı ışığı; Uzun huzmeli farların açık olduğunu gösterir."),
            AracGostergeIsaret(id: 52, aracGostergeImage: "agpi52", aracGosterge: "Yakıt filtresi ikaz ışığı; Yakıt filtresinin kirli veya aşınmış olduğunu gösteren bir uyarı ışığı. Yakıt filtresini mümkün olan en kısa sürede temizlemeli veya değiştirmelisiniz."),


        ]
        return aracGostergePaneliVeriler
    }
}
